### ISSUE TITLE
Removing scroll and use the edges when in full-screen mode

### ISSUE THREAD

**Issue by afshinm** [fmoralesc/neovim-gnome-terminal-wrapper#24]
Hey guys,

Thanks for this cool / simple app! 

I have two issues that are visible in following screenshot: 

![screenshot from 2017-09-27 10-20-25](https://user-images.githubusercontent.com/314326/30905738-9e36c598-a36d-11e7-9b05-25460a193ace.png)

- Removing the vertical scroll
- using the entire screen when in full-screen mode (you can see two background colors, one for Vim and one for zsh)

I'm happy to send a PR but I'm not sure how to fix it.

**Comment by fmoralesc** [comment]
Sorry for missing this! :/

The second issue should be fixed in recent versions of gnome-terminal. For the first,  I simply disable the scrollbar for gnome-terminal globally (or in whatever profile you use); I've found I never miss it. I don't think there is an option to launch it without the scrollbars without doing that.
